spring:
  application:
    name: ticketgo-back-end
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticketgo_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: PhuongTay110903@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# Email sender account
email:
  username: phuongtay713@gmail.com
  password: mlfoeesojdrbhbez

# Frontend
frontend:
  url: http://localhost:3000

# JWT private & public key
jwt:
  private:
    key:
      path: src/main/resources/private_key.pem
  public:
    key:
      path: src/main/resources/public_key.pem

# Cloudinary
cloudinary:
  cloud-name: dj1h07rea
  api-key: 854269645733317
  api-secret: BDjF4Xe77SeLhGROvkvZkwAi928

