spring:
  application:
    name: ticketgo-back-end
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticketgo_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: PhuongTay110903@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

# Email sender account
email:
  username: phuongtay713@gmail.com
  password: mlfoeesojdrbhbez

# Frontend
frontend:
  url: http://localhost:3000

# Jwt secret
jwt:
  secret: 843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3

# Cloudinary
cloudinary:
  cloud-name: dj1h07rea
  api-key: 854269645733317
  api-secret: BDjF4Xe77SeLhGROvkvZkwAi928